# Generated by Django 5.2.7 on 2025-11-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_comment', '0004_commentattachment_delete_commentimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentattachment',
            name='file',
            field=models.FileField(upload_to='product/'),
        ),
    ]
