# Generated by Django 5.2.7 on 2025-11-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_comment', '0005_alter_commentattachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='guest_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commentattachment',
            name='attachment_type',
            field=models.CharField(choices=[('image', 'Image'), ('text', 'Text File')], default='image', max_length=5),
        ),
        migrations.AlterField(
            model_name='commentattachment',
            name='file',
            field=models.FileField(upload_to='products/%Y/%m/%d/'),
        ),
    ]
