# Generated by Django 5.2.7 on 2025-11-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_comment', '0006_comment_guest_email_comment_guest_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentattachment',
            name='file',
            field=models.FileField(upload_to='comment_attachments/%Y/%m/%d/'),
        ),
    ]
