# Generated by Django 5.2.7 on 2025-10-30 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0002_user_avatar_user_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='publich_id',
            new_name='public_id',
        ),
    ]
