# Generated by Django 5.2.7 on 2025-11-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0003_rename_publich_id_user_public_id'),
    ]
