# Generated by Django 5.2.7 on 2025-11-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_comment', '0002_alter_comment_options_rename_body_comment_text_and_more'),
        ('core_user', '0004_user_posts_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comments_liked',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='core_comment.comment'),
        ),
    ]
