# Generated by Django 5.2.7 on 2025-11-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0005_user_comments_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
